-- Esquema inicial de RASTREADOC para Supabase.
-- Ejecutar una sola vez desde SQL Editor en el proyecto correspondiente.

create extension if not exists pgcrypto;
create extension if not exists citext;

do $$
begin
  create type public.document_status as enum (
    'EN_OFICINA',
    'ENVIADO',
    'AUTORIZADO',
    'RECHAZADO',
    'REENVIADO'
  );
exception
  when duplicate_object then null;
end
$$;

create table if not exists public.agencies (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique check (length(trim(name::text)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.document_types (
  id uuid primary key default gen_random_uuid(),
  name citext not null unique check (length(trim(name::text)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.case_files (
  id uuid primary key default gen_random_uuid(),
  number citext not null unique check (length(trim(number::text)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  case_file_id uuid not null references public.case_files(id) on delete restrict,
  document_type_id uuid not null references public.document_types(id) on delete restrict,
  agency_id uuid not null references public.agencies(id) on delete restrict,
  status public.document_status not null default 'EN_OFICINA',
  qr_token uuid not null unique default gen_random_uuid(),
  last_movement_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists documents_case_file_id_idx on public.documents(case_file_id);
create index if not exists documents_status_idx on public.documents(status);
create index if not exists documents_agency_id_idx on public.documents(agency_id);

create table if not exists public.movements (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.documents(id) on delete restrict,
  status public.document_status not null,
  occurred_at timestamptz not null default now(),
  rejection_reason text,
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  constraint rejection_reason_length check (
    rejection_reason is null or length(rejection_reason) <= 250
  )
);

create index if not exists movements_document_date_idx
  on public.movements(document_id, occurred_at desc);

create or replace function public.create_initial_movement()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  insert into public.movements (document_id, status, occurred_at, created_by)
  values (new.id, new.status, new.created_at, auth.uid());
  return new;
end;
$$;

drop trigger if exists document_initial_movement on public.documents;
create trigger document_initial_movement
after insert on public.documents
for each row execute function public.create_initial_movement();

create or replace function public.sync_document_status()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.documents
  set status = new.status, last_movement_at = new.occurred_at
  where id = new.document_id;
  return new;
end;
$$;

drop trigger if exists movement_sync_document on public.movements;
create trigger movement_sync_document
after insert on public.movements
for each row execute function public.sync_document_status();

create or replace function public.prevent_movement_changes()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'El historial de movimientos no se puede modificar ni eliminar.';
end;
$$;

drop trigger if exists movements_are_immutable on public.movements;
create trigger movements_are_immutable
before update or delete on public.movements
for each row execute function public.prevent_movement_changes();

alter table public.agencies enable row level security;
alter table public.document_types enable row level security;
alter table public.case_files enable row level security;
alter table public.documents enable row level security;
alter table public.movements enable row level security;

drop policy if exists "authenticated_agencies" on public.agencies;
create policy "authenticated_agencies" on public.agencies
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_document_types" on public.document_types;
create policy "authenticated_document_types" on public.document_types
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_case_files" on public.case_files;
create policy "authenticated_case_files" on public.case_files
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_documents" on public.documents;
create policy "authenticated_documents" on public.documents
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_movements_read" on public.movements;
create policy "authenticated_movements_read" on public.movements
for select to authenticated using (true);

drop policy if exists "authenticated_movements_insert" on public.movements;
create policy "authenticated_movements_insert" on public.movements
for insert to authenticated with check (created_by = auth.uid());

revoke all on public.agencies, public.document_types, public.case_files,
  public.documents, public.movements from anon;

grant select, insert on public.agencies, public.document_types,
  public.case_files, public.documents to authenticated;
grant select, insert on public.movements to authenticated;
grant usage, select on sequence public.movements_id_seq to authenticated;
